featured_user:
  default: ""
  type: string

featured_user_banner_text_above:
  default: ""
  type: string
  textarea: true

featured_user_banner_text_below:
  default: ""
  type: string
  textarea: true

featured_user_banner_text_align:
  default: center
  type: enum
  choices:
    - right
    - left

featured_user_banner_display_start_date:
  default: ""
  type: string

featured_user_banner_display_end_date:
  default: ""
  type: string

featured_user_banner_display_on_homepage:
  default: true
  type: bool

featured_user_banner_border_color:
  default: "var(--primary)"
  type: string
  
featured_user_banner_border_thickness:
  default: 3
  type: integer
  min: 1

featured_user_banner_border_roundness:
  default: 10
  type: integer
  min: 1

auto_resize_banner:
  default: false
  type: bool

featured_user_show_featured_icon_in_user_card:
  default: true
  type: bool

featured_user_featured_icon_in_user_card:
  default: "award"
  type: string

featured_user_featured_icon_color_on_user_card:
  default: "var(--gold)"
  type: string

display_total_likes_given:
  default: true
  type: bool

display_total_likes_received:
  default: true
  type: bool

display_total_post_count:
  default: false
  type: bool

display_total_topic_count:
  default: false
  type: bool

display_total_read_time:
  default: false
  type: bool

display_total_days_visited:
  default: true
  type: bool
