featured_user:
  default: ""
  type: string

featured_user_banner_text:
  default: ""
  type: string

featured_user_banner_display_start_date:
  default: ""
  type: string

featured_user_banner_display_end_date:
  default: ""
  type: string

display_total_likes_given:
  default: true
  type: bool

display_total_likes_received:
  default: true
  type: bool

display_total_post_count:
  default: false
  type: bool

display_total_topic_count:
  default: false
  type: bool

display_total_read_time:
  default: false
  type: bool

display_total_days_visited:
  default: true
  type: bool

display_title:
  default: true
  type: bool
